package com.cc.dao;

import com.cc.model.MenuDO;
import com.cc.pojo.MenuList;

import java.util.List;

public interface MenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int insert(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int insertSelective(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    MenuDO selectByPrimaryKey(Integer menuId);
    List<MenuDO> selectByMenuParentId(Integer MenuParentId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int updateByPrimaryKeySelective(MenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int updateByPrimaryKey(MenuDO record);
}