package com.cc.dao;

import com.cc.model.RoleMenuDO;

public interface RoleMenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int deleteByPrimaryKey(Integer roleMenuId);
    int deleteRoleMenu(Integer roleId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int insert(RoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int insertSelective(RoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    RoleMenuDO selectByPrimaryKey(Integer roleMenuId);
    RoleMenuDO selectByGetRoleId(Integer roleId);
    RoleMenuDO selectByGetMenuId(Integer menuId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int updateByPrimaryKeySelective(RoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int updateByPrimaryKey(RoleMenuDO record);
}