package com.cc.dao;

import com.cc.model.UserRoleDO;
import com.cc.pojo.UserRoleList;

import java.util.List;
import java.util.Set;

public interface UserRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int deleteByPrimaryKey(Integer userRoleId);
    int deleteUserRole(Integer roleId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int insert(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int insertSelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    UserRoleDO selectByPrimaryKey(Integer userRoleId);
    UserRoleDO selectByGetRoleId(int roleId);
    UserRoleDO selectByGetUserId(int userId);
    Set<UserRoleList> selectUserRoleList(int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int updateByPrimaryKeySelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    int updateByPrimaryKey(UserRoleDO record);
}