package com.cc.model;

import java.util.Date;

public class RoleMenuDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_menu_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Integer roleMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.update_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.create_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.delete_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Date deleteAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_menu_id
     *
     * @return the value of role_menu.role_menu_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Integer getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_menu_id
     *
     * @param roleMenuId the value for role_menu.role_menu_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setRoleMenuId(Integer roleMenuId) {
        this.roleMenuId = roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_id
     *
     * @return the value of role_menu.role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_id
     *
     * @param roleId the value for role_menu.role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu_id
     *
     * @return the value of role_menu.menu_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu_id
     *
     * @param menuId the value for role_menu.menu_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.update_at
     *
     * @return the value of role_menu.update_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.update_at
     *
     * @param updateAt the value for role_menu.update_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.create_at
     *
     * @return the value of role_menu.create_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.create_at
     *
     * @param createAt the value for role_menu.create_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.delete_at
     *
     * @return the value of role_menu.delete_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.delete_at
     *
     * @param deleteAt the value for role_menu.delete_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }
}