package com.cc.model;

import java.util.Date;

public class UserRoleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Integer userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.upadte_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Date upadteAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.create_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.delete_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    private Date deleteAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_role_id
     *
     * @return the value of user_role.user_role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_role_id
     *
     * @param userRoleId the value for user_role.user_role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_id
     *
     * @return the value of user_role.user_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_id
     *
     * @param userId the value for user_role.user_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_id
     *
     * @return the value of user_role.role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_id
     *
     * @param roleId the value for user_role.role_id
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.upadte_at
     *
     * @return the value of user_role.upadte_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Date getUpadteAt() {
        return upadteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.upadte_at
     *
     * @param upadteAt the value for user_role.upadte_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setUpadteAt(Date upadteAt) {
        this.upadteAt = upadteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.create_at
     *
     * @return the value of user_role.create_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.create_at
     *
     * @param createAt the value for user_role.create_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.delete_at
     *
     * @return the value of user_role.delete_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.delete_at
     *
     * @param deleteAt the value for user_role.delete_at
     *
     * @mbg.generated Fri Mar 29 09:37:13 CST 2019
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }
}